# Generated by Django 3.0.3 on 2020-02-23 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addlecture', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='lecture',
        ),
        migrations.DeleteModel(
            name='Lecture',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
