# Generated by Django 3.0.3 on 2020-02-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200224_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='personal_score',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], default='None', max_length=3),
        ),
    ]
