# Generated by Django 3.0.3 on 2020-02-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200224_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='personal_score',
            field=models.CharField(choices=[('★☆☆☆☆', 1), ('★★☆☆☆', 2), ('★★★☆☆', 3), ('★★★★☆', 4), ('★★★★★', 5)], default='None', max_length=10),
        ),
    ]
