# Generated by Django 3.0.3 on 2020-02-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200224_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='personal_score',
            field=models.CharField(choices=[('★☆☆☆☆', '★☆☆☆☆'), ('★★☆☆☆', '★★☆☆☆'), ('★★★☆☆', '★★★☆☆'), ('★★★★☆', '★★★★☆'), ('★★★★★', '★★★★★')], default='None', max_length=10),
        ),
    ]
